### ISSUE TITLE
Service Template not working with OpenNebula > 5.12

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/terraform-provider-opennebula#178]
`TestAccServiceTemplate` test is failing when testing the provider against OpenNebula version > 5.12:

```
=== RUN   TestAccServiceTemplate
    testing.go:715: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: <!DOCTYPE html>

...

--- FAIL: TestAccServiceTemplate (0.32s)
=== RUN   TestAccService
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xfb42a7]
```

The complete error can be found [here](https://github.com/OpenNebula/terraform-provider-opennebula/runs/4140792742?check_suite_focus=true).

**Comment by frousselet** [comment]
Hi @christian7007, @treywelsh, @jaypif,

I don't understand the status on the `OpenNebula>5.12` acceptance tests.
Could you clarify what changes need to be done in order to fix it please?

**Related:**

#188 
https://github.com/OpenNebula/one/commit/c440bc9af7de36d3da2746401ce7c59c0f4c7bfc

Since the next LTS will be released soon, we might want to prioritize this issue.

I created the label [`needs-ci-6_2-fix`](https://github.com/OpenNebula/terraform-provider-opennebula/pulls?q=is%3Apr+is%3Aopen+label%3Aneeds-ci-6_2-fix) for issues needing the `6_2` pipeline.

We also might want to add a `6_4` pipeline.

**Comment by frousselet** [comment]
As seen with @christian7007,

The pipeline [works](https://github.com/OpenNebula/terraform-provider-opennebula/runs/6367787890?check_suite_focus=true) (excluding API changes) with OpenNebula `>=6.3.90`.

- The `6_2` pipeline will be dropped once `6.4` is released
- The `5_12` pipeline will be dropped once `5.12.12 'Firework' EE LTS` is officially flagged as end-of-life
