### PR TITLE
B #178: Add compatibility with OneFlow server > 5.12.x

### LINKED ISSUE #178: Service Template not working with OpenNebula > 5.12
`TestAccServiceTemplate` test is failing when testing the provider against OpenNebula version > 5.12:

```
=== RUN   TestAccServiceTemplate
    testing.go:715: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: <!DOCTYPE html>

...

--- FAIL: TestAccServiceTemplate (0.32s)
=== RUN   TestAccService
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xfb42a7]
```

The complete error can be found [here](https://github.com/OpenNebula/terraform-provider-opennebula/runs/4140792742?check_suite_focus=true).

### PR DESCRIPTION
**Pull request by christian7007**
It also requires: https://github.com/OpenNebula/one/commit/c440bc9af7de36d3da2746401ce7c59c0f4c7bfc

### CODE REVIEW

**Comment by treywelsh** [comment]
To sum up the fix mentioned below should be available from OpenNebula 6.2.1 release.
According to @christian7007 tests, the provider acceptance tests passes

File: .ci_scripts/oned.sh [hunk 1]
```diff
@@ -21,10 +21,14 @@ mkdir ~/.one
 echo 'oneadmin:opennebula' > ~/.one/one_auth
 
 # Enable dummy drivers
-sudo chmod o+w /etc/one/oned.conf
+sudo chmod o+wr /etc/one/oned.conf
 sudo chmod o+w /etc/one/monitord.conf
+sudo chmod 777 /etc/one
```
Comment (jaypif) [inline .ci_scripts/oned.sh:26]: I am not sure this is correct.

This is quite dangerous to configure this file with such rights.

Is it the same on prod ?

Mayby o+x is enough

Comment (christian7007) [reply .ci_scripts/oned.sh:26]: No, for production the permission for `oned.conf` should be:

```
-rw-r----- 1 root oneadmin 57318 Oct 21 10:17 /etc/one/oned.conf
```

The problem is that the CI tests run under an unprivileged user, so in order to properly carry the required modifications we need write and execution permissions. I added that to ensure that we avoid permissions related errors, as we're running the tests in a controlled scenario. IMHO changing the configuration file shouldn't lead to any security issues in this specific environment, but please let me know if you think otherwise and I'll try to address any possible issue.

Comment (jaypif) [reply .ci_scripts/oned.sh:26]: I understand CI constraint. I just wanted to be sure it is not the same rule in production :).

Thanks

**Review by jaypif — APPROVED** [review]
